//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// 原始文件名:
// 生成日期: 2012-6-26 21:11:41
namespace LinqTest
{
    
    /// <summary>
    /// 架构中不存在 EntityContainer 的注释。
    /// </summary>
    public partial class EntityContainer : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// 请使用应用程序配置文件的“EntityContainer”部分中的连接字符串初始化新 EntityContainer 对象。
        /// </summary>
        public EntityContainer() : 
                base("name=EntityContainer", "EntityContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 EntityContainer 对象。
        /// </summary>
        public EntityContainer(string connectionString) : 
                base(connectionString, "EntityContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 EntityContainer 对象。
        /// </summary>
        public EntityContainer(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "EntityContainer")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
    }
}
